jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - kube-orb/install-kubectl
      
      - run:
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
            sudo unzip terraform_0.12.26_linux_amd64.zip -d /usr/local/bin
          name: Install Terraform

      - run:
          name: Run tests
          command: |
            make test

orbs:
  go: circleci/go@0.2.0
  kube-orb: circleci/kubernetes@1.10.0
version: 2.1
workflows:
  default:
    jobs:
      - test

  version: 2
